added the container for loading asset bundles from cloud.
atomata/VClassroom_Proto_VSolar_ApparatusUPackageDevelopment pull request #13
Opened 2021-11-11 19:14 UTC by Ysabz

this PR:

- readds the removed container script for loading asset bundles from cloud
- adds prefab and apparatus provider for cloud assets 
- fixes the exampleassetbundlecloud scene
- updates the player setting for avoiding code stripping. ( caused "could not produce the class with id x"  code stripping was causing the animator code to be stripped and as such animation toggles could not be run )

2021-11-11 22:33 UTC, hexthedev requested changes

2021-11-11 22:33 UTC, hexthedev commented on Assets/Dependencies/Atomata/Apparatus/Runtime/Scripts/AssetLoading/ApparatusProvider/CloudApparatusProvider.cs
> +            }
You can just wait the webrequest. I think `await UnityWebRequest.Get(url) works`

2021-11-11 22:33 UTC, hexthedev commented on Assets/Dependencies/Atomata/Apparatus/Runtime/Scripts/AssetLoading/PrefabProvider/CloudAssetProvider.cs
> +            }
again, direct await works with UniTask

2021-12-13 16:06 UTC, Ysabz commented on Assets/Dependencies/Atomata/Apparatus/Runtime/Scripts/AssetLoading/ApparatusProvider/CloudApparatusProvider.cs
> +            }
@hexthedev , I tried await UnityWebRequest.Get(url) but it gives this compiler error : The type 'UnityEngine.Networking.UnityWebRequest' cannot be used as type parameter 'T' in the generic type or method 'EnumeratorAsyncExtensions.GetAwaiter<T>(T)'. There is no implicit reference conversion from 'UnityEngine.Networking.UnityWebRequest' to 'System.Collections.IEnumerator'.

2021-12-14 00:28 UTC, hexthedev commented on Assets/Dependencies/Atomata/Apparatus/Runtime/Scripts/AssetLoading/ApparatusProvider/CloudApparatusProvider.cs
> +            }
So I think the awaiter dosen't come with UniTask like I thought. 

Try adding this as a Utility in the Apparatus Library: https://gist.github.com/mattyellen/d63f1f557d08f7254345bff77bfdc8b3. It should work after that. 

The reason I'm flagging this is because `Delay(100)` is generally not a good way to do stuff. Sometimes you have no choice like in embedded programming, but in our case we can avoid it. Waiting 100ms is too arbitrary and wastes some cpu time. 

The awaiter above will do the job. You can also do a coroutine. 

```
IEnumerator Request() {
   UnityWebRequest req = UnityWebRequest.Get(url);
   UnityWebRequestAsyncOperation op = req.SendWebRequest();
    
   while (!op.isDone)
   {
     yeild return new WaitForEndOfFrame();
   }
}
```

This is better cause you're throttled by the frame rate instead, which is reasonable since you're only presented images at the framerate.

2022-01-05 00:18 UTC, hexthedev commented
Just gonna merge, my comment wasn't a big deal

2022-01-05 00:18 UTC, merged